[package]
name = "Chromia"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#testing
rand = "0.7.0"

#System Info
chrono = "0.4"
sysinfo = "0.31.2"
nix = "0.23.0"
byteorder = "1.4"


#Netowrking
<<<<<<< HEAD
port_scanner = "0.1.5"
=======
pnet = "0.35.0"
rust-ini = "0.21.1"
serde_json = "1.0.127"
>>>>>>> main
