[package]
name = "anomaly_detection_hids"
version = "0.1.0"
edition = "2021"

[dependencies]
notify = "5.0"
serde_json = "1.0"
chrono = "0.4"
tokio = { version = "1.0", features = ["full"] }
hyper = { version = "0.14", features = ["full"] }
log = "0.4"
dirs = "4.0"
rand = "0.8"
regex = "1.5"
syslog = "6.1"

