[package]
name = "Chromia"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#testing
rand = "0.7.0"

#System Info
chrono = "0.4"
sysinfo = "0.31.2"

#Netowrking
pnet = "0.35.0"